### ISSUE TITLE
Attempting to undo rekeying on a singlesig account rekeyed to a multisig shared between ios and android devices

### ISSUE THREAD

**Issue by aorumbayev** [blockshake-io/defly-connect#18]
I observed a bug on TestNet when dealing with multi device multi sig accounts in defly. Assume latest versions of both ios and android clients at the moment of reporting this issue.

Steps to reproduce:

1. Made 2 fresh wallets. A is on ios the B on android. 
2. Added A to android as watch account 
3. Created an msig on Android with A (watch account) and B (b has pkey)
4. Imported msig to ios 
5. Attempted to use native app rekey feature on a random wallet C on ios (rekeyed to msig), to be rekeyed back to itself. Given that msig is imported on both devices, on iOS it gets the signature correctly then awaits for android to pick it up. Android never receives the notification though. 

I am not sure if its because multisig is created from a combination of a single sig with pkey on device and a singlesig from second device imported as a watch account OR because its cross OS communication. If yes, then what's the point of using multisigs if they force user to still have access to all pkeys? What if you are sharing the msig among team members and don't want to expose your pkey on their devices?

**Comment by aorumbayev** [comment]
same behaviour on MainNet except that the other device does get the notification put clicking sign fails and that's it

**Comment by k13n** [comment]
Thanks for reporting! This is just a quick ACK that I've seen your bug report and that I'm looking into it. I'm currently out of office and will have more time next week to dig deeper. I'll get back to you then!

**Comment by k13n** [comment]
@aorumbayev, is your account C imported as full account or watch account on both of your devices? I'm guessing it's missing on your Android device because you don't get a push notification to sign.

The reason why we don't send a push notification in this case is for spam protection. Assume that you have a multisig between accounts A & B and that the multisig is imported on both of your devices. Now an "attacker" creates a random account C, rekeys it to your multisig, and then tries to rekey C back to itself. It would be bad if you get a (push) notification to sign on behalf of C (since C is rekeyed to your multisig) because you didn't initiate that transaction. We only send you a notification if you agreed to this by importing account C as watch account or full account.

**Comment by aorumbayev** [comment]
@k13n so account C in my case was not directly imported nor was it in watch mode on android. 

So its possible to add C as watch account without pk on android and thats sufficient for rekey on C initiated from ios to work on android (sharing same multisig with ios)? 

If thats the case, a minor enhancement on a wallet UI could save a lot of time and confusion for folks. Something like an extra label that appears after N seconds that gives a link to a docs page explaining various edge cases with multisigs on multi-device scenarios + some troubleshooting tips.

**Comment by k13n** [comment]
> So its possible to add C as watch account without pk on android and thats sufficient for rekey on C initiated from ios to work on android (sharing same multisig with ios)?

Yes, that should be sufficient. It'd be great if you could verify that on your end and let me know if there's any other problem.

> If thats the case, a minor enhancement on a wallet UI could save a lot of time and confusion for folks. Something like an extra label that appears after N seconds that gives a link to a docs page explaining various edge cases with multisigs on multi-device scenarios + some troubleshooting tips.

It's true that multisigs and rekeying have a lot of edge cases and they should be documented better.
